In [1]:
import pandas as pd
import numpy as np
import nltk

In [2]:
from nltk.corpus import stopwords
stop = stopwords.words('english')

In [3]:
df = pd.read_csv("/home/devjith/Luminar/Machine Learning/files/DisneylandReviews.csv",encoding='ISO-8859-1')

In [4]:
df

,Review_ID,Rating,Year_Month,Reviewer_Location,Review_Text,Branch
0,670772142,4,2019-4,Australia,If you've ever been to Disneyland anywhere you...,Disneyland_HongKong
1,670682799,4,2019-5,Philippines,Its been a while since d last time we visit HK...,Disneyland_HongKong
2,670623270,4,2019-4,United Arab Emirates,Thanks God it wasn t too hot or too humid wh...,Disneyland_HongKong
3,670607911,4,2019-4,Australia,HK Disneyland is a great compact park. Unfortu...,Disneyland_HongKong
4,670607296,4,2019-4,United Kingdom,"the location is not in the city, took around 1...",Disneyland_HongKong
...,...,...,...,...,...,...
42651,1765031,5,missing,United Kingdom,i went to disneyland paris in july 03 and thou...,Disneyland_Paris
42652,1659553,5,missing,Canada,2 adults and 1 child of 11 visited Disneyland ...,Disneyland_Paris
42653,1645894,5,missing,South Africa,My eleven year old daughter and myself went to...,Disneyland_Paris
42654,1618637,4,missing,United States,"This hotel, part of the Disneyland Paris compl...",Disneyland_Paris
42655,1536786,4,missing,United Kingdom,"I went to the Disneyparis resort, in 1996, wit...",Disneyland_Paris

In [5]:
df = df.drop(columns='Review_ID')

In [6]:
df

,Rating,Year_Month,Reviewer_Location,Review_Text,Branch
0,4,2019-4,Australia,If you've ever been to Disneyland anywhere you...,Disneyland_HongKong
1,4,2019-5,Philippines,Its been a while since d last time we visit HK...,Disneyland_HongKong
2,4,2019-4,United Arab Emirates,Thanks God it wasn t too hot or too humid wh...,Disneyland_HongKong
3,4,2019-4,Australia,HK Disneyland is a great compact park. Unfortu...,Disneyland_HongKong
4,4,2019-4,United Kingdom,"the location is not in the city, took around 1...",Disneyland_HongKong
...,...,...,...,...,...
42651,5,missing,United Kingdom,i went to disneyland paris in july 03 and thou...,Disneyland_Paris
42652,5,missing,Canada,2 adults and 1 child of 11 visited Disneyland ...,Disneyland_Paris
42653,5,missing,South Africa,My eleven year old daughter and myself went to...,Disneyland_Paris
42654,4,missing,United States,"This hotel, part of the Disneyland Paris compl...",Disneyland_Paris
42655,4,missing,United Kingdom,"I went to the Disneyparis resort, in 1996, wit...",Disneyland_Paris

In [7]:
df = df.drop(columns=['Year_Month'])

In [8]:
df

,Rating,Reviewer_Location,Review_Text,Branch
0,4,Australia,If you've ever been to Disneyland anywhere you...,Disneyland_HongKong
1,4,Philippines,Its been a while since d last time we visit HK...,Disneyland_HongKong
2,4,United Arab Emirates,Thanks God it wasn t too hot or too humid wh...,Disneyland_HongKong
3,4,Australia,HK Disneyland is a great compact park. Unfortu...,Disneyland_HongKong
4,4,United Kingdom,"the location is not in the city, took around 1...",Disneyland_HongKong
...,...,...,...,...
42651,5,United Kingdom,i went to disneyland paris in july 03 and thou...,Disneyland_Paris
42652,5,Canada,2 adults and 1 child of 11 visited Disneyland ...,Disneyland_Paris
42653,5,South Africa,My eleven year old daughter and myself went to...,Disneyland_Paris
42654,4,United States,"This hotel, part of the Disneyland Paris compl...",Disneyland_Paris
42655,4,United Kingdom,"I went to the Disneyparis resort, in 1996, wit...",Disneyland_Paris

In [9]:
text = df['Review_Text']

In [10]:
from nltk.tokenize import TweetTokenizer,word_tokenize
tk = TweetTokenizer()

In [11]:
text = text.apply(lambda x: tk.tokenize(x)).apply(lambda x: ' '.join(x))

In [12]:
import re
text = text.apply(lambda x: re.sub('[^a-zA-Z0-9]',' ',x))

In [13]:
text = text.apply(lambda x: ' '.join([i for i in word_tokenize(x) if len(i)>=3]))

In [14]:
from nltk.stem import SnowballStemmer
stemmer = SnowballStemmer(language='english')

text = text.apply(lambda x : ' '.join([stemmer.stem(i.lower()) for i in word_tokenize(x)]))

In [15]:
text = text.apply(lambda x: ' '.join([i for i in word_tokenize(x) if i not in stop]))

In [16]:
from sklearn.feature_extraction.text import TfidfVectorizer
vector = TfidfVectorizer()

vect_text = vector.fit_transform(text)
type(vect_text)

scipy.sparse._csr.csr_matrix

In [ ]:
tfidf_df = pd.DataFrame(vect_text.toarray(), columns=vector.get_feature_names_out())
df = pd.concat([df, tfidf_df], axis=1)
df = df.drop(columns=['Review_Text'])

In [ ]:
df

,Rating,Reviewer_Location,Review_Text,Branch
0,4,Australia,<Compressed Sparse Row sparse matrix of dtype ...,Disneyland_HongKong
1,4,Philippines,<Compressed Sparse Row sparse matrix of dtype ...,Disneyland_HongKong
2,4,United Arab Emirates,<Compressed Sparse Row sparse matrix of dtype ...,Disneyland_HongKong
3,4,Australia,<Compressed Sparse Row sparse matrix of dtype ...,Disneyland_HongKong
4,4,United Kingdom,<Compressed Sparse Row sparse matrix of dtype ...,Disneyland_HongKong
...,...,...,...,...
42651,5,United Kingdom,<Compressed Sparse Row sparse matrix of dtype ...,Disneyland_Paris
42652,5,Canada,<Compressed Sparse Row sparse matrix of dtype ...,Disneyland_Paris
42653,5,South Africa,<Compressed Sparse Row sparse matrix of dtype ...,Disneyland_Paris
42654,4,United States,<Compressed Sparse Row sparse matrix of dtype ...,Disneyland_Paris
42655,4,United Kingdom,<Compressed Sparse Row sparse matrix of dtype ...,Disneyland_Paris

In [ ]:
df_enc = pd.get_dummies(df[['Reviewer_Location','Branch']],drop_first=True,dtype=int)

In [ ]:
df = df.drop(columns=['Reviewer_Location','Branch'])
df = pd.concat([df,df_enc],axis=1)

In [ ]:
df

,Rating,Review_Text,Reviewer_Location
0,4,<Compressed Sparse Row sparse matrix of dtype ...,1.0
1,4,<Compressed Sparse Row sparse matrix of dtype ...,0.0
2,4,<Compressed Sparse Row sparse matrix of dtype ...,NaN
3,4,<Compressed Sparse Row sparse matrix of dtype ...,NaN
4,4,<Compressed Sparse Row sparse matrix of dtype ...,NaN
...,...,...,...
42651,5,<Compressed Sparse Row sparse matrix of dtype ...,NaN
42652,5,<Compressed Sparse Row sparse matrix of dtype ...,NaN
42653,5,<Compressed Sparse Row sparse matrix of dtype ...,NaN
42654,4,<Compressed Sparse Row sparse matrix of dtype ...,NaN
42655,4,<Compressed Sparse Row sparse matrix of dtype ...,NaN