In [125]:
import pandas as pd
import numpy as np

In [126]:
df = pd.read_csv("/home/devjith/Luminar/Machine Learning/files/SuperMarket Analysis.csv")

In [127]:
df

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Sales,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,750-67-8428,Alex,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,1:08:00 PM,Ewallet,522.83,4.761905,26.1415,9.1
1,226-31-3081,Giza,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,3/8/2019,10:29:00 AM,Cash,76.40,4.761905,3.8200,9.6
2,631-41-3108,Alex,Yangon,Normal,Female,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,1:23:00 PM,Credit card,324.31,4.761905,16.2155,7.4
3,123-19-1176,Alex,Yangon,Member,Female,Health and beauty,58.22,8,23.2880,489.0480,1/27/2019,8:33:00 PM,Ewallet,465.76,4.761905,23.2880,8.4
4,373-73-7910,Alex,Yangon,Member,Female,Sports and travel,86.31,7,30.2085,634.3785,2/8/2019,10:37:00 AM,Ewallet,604.17,4.761905,30.2085,5.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,233-67-5758,Giza,Naypyitaw,Normal,Male,Health and beauty,40.35,1,2.0175,42.3675,1/29/2019,1:46:00 PM,Ewallet,40.35,4.761905,2.0175,6.2
996,303-96-2227,Cairo,Mandalay,Normal,Female,Home and lifestyle,97.38,10,48.6900,1022.4900,3/2/2019,5:16:00 PM,Ewallet,973.80,4.761905,48.6900,4.4
997,727-02-1313,Alex,Yangon,Member,Male,Food and beverages,31.84,1,1.5920,33.4320,2/9/2019,1:22:00 PM,Cash,31.84,4.761905,1.5920,7.7
998,347-56-2442,Alex,Yangon,Normal,Male,Home and lifestyle,65.82,1,3.2910,69.1110,2/22/2019,3:33:00 PM,Cash,65.82,4.761905,3.2910,4.1
999,849-09-3807,Alex,Yangon,Member,Female,Fashion accessories,88.34,7,30.9190,649.2990,2/18/2019,1:28:00 PM,Cash,618.38,4.761905,30.9190,6.6

In [128]:
df = df.drop(columns='Invoice ID')

In [129]:
df['Branch'].unique()

array(['Alex', 'Giza', 'Cairo'], dtype=object)

In [130]:
df.dtypes

Branch                      object
City                        object
Customer type               object
Gender                      object
Product line                object
Unit price                 float64
Quantity                     int64
Tax 5%                     float64
Sales                      float64
Date                        object
Time                        object
Payment                     object
cogs                       float64
gross margin percentage    float64
gross income               float64
Rating                     float64
dtype: object

In [131]:
df['Date'] = pd.to_datetime(df['Date'])

In [132]:
df

,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Sales,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,Alex,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,2019-01-05,1:08:00 PM,Ewallet,522.83,4.761905,26.1415,9.1
1,Giza,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,2019-03-08,10:29:00 AM,Cash,76.40,4.761905,3.8200,9.6
2,Alex,Yangon,Normal,Female,Home and lifestyle,46.33,7,16.2155,340.5255,2019-03-03,1:23:00 PM,Credit card,324.31,4.761905,16.2155,7.4
3,Alex,Yangon,Member,Female,Health and beauty,58.22,8,23.2880,489.0480,2019-01-27,8:33:00 PM,Ewallet,465.76,4.761905,23.2880,8.4
4,Alex,Yangon,Member,Female,Sports and travel,86.31,7,30.2085,634.3785,2019-02-08,10:37:00 AM,Ewallet,604.17,4.761905,30.2085,5.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,Giza,Naypyitaw,Normal,Male,Health and beauty,40.35,1,2.0175,42.3675,2019-01-29,1:46:00 PM,Ewallet,40.35,4.761905,2.0175,6.2
996,Cairo,Mandalay,Normal,Female,Home and lifestyle,97.38,10,48.6900,1022.4900,2019-03-02,5:16:00 PM,Ewallet,973.80,4.761905,48.6900,4.4
997,Alex,Yangon,Member,Male,Food and beverages,31.84,1,1.5920,33.4320,2019-02-09,1:22:00 PM,Cash,31.84,4.761905,1.5920,7.7
998,Alex,Yangon,Normal,Male,Home and lifestyle,65.82,1,3.2910,69.1110,2019-02-22,3:33:00 PM,Cash,65.82,4.761905,3.2910,4.1
999,Alex,Yangon,Member,Female,Fashion accessories,88.34,7,30.9190,649.2990,2019-02-18,1:28:00 PM,Cash,618.38,4.761905,30.9190,6.6

In [133]:
df.dtypes

Branch                             object
City                               object
Customer type                      object
Gender                             object
Product line                       object
Unit price                        float64
Quantity                            int64
Tax 5%                            float64
Sales                             float64
Date                       datetime64[ns]
Time                               object
Payment                            object
cogs                              float64
gross margin percentage           float64
gross income                      float64
Rating                            float64
dtype: object

In [134]:
df['Day'] = df['Date'].dt.day
df['Month'] = df['Date'].dt.month
df['Year'] = df['Date'].dt.year
df = df.drop(columns='Date')
df

,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Sales,Time,Payment,cogs,gross margin percentage,gross income,Rating,Day,Month,Year
0,Alex,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1:08:00 PM,Ewallet,522.83,4.761905,26.1415,9.1,5,1,2019
1,Giza,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,10:29:00 AM,Cash,76.40,4.761905,3.8200,9.6,8,3,2019
2,Alex,Yangon,Normal,Female,Home and lifestyle,46.33,7,16.2155,340.5255,1:23:00 PM,Credit card,324.31,4.761905,16.2155,7.4,3,3,2019
3,Alex,Yangon,Member,Female,Health and beauty,58.22,8,23.2880,489.0480,8:33:00 PM,Ewallet,465.76,4.761905,23.2880,8.4,27,1,2019
4,Alex,Yangon,Member,Female,Sports and travel,86.31,7,30.2085,634.3785,10:37:00 AM,Ewallet,604.17,4.761905,30.2085,5.3,8,2,2019
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,Giza,Naypyitaw,Normal,Male,Health and beauty,40.35,1,2.0175,42.3675,1:46:00 PM,Ewallet,40.35,4.761905,2.0175,6.2,29,1,2019
996,Cairo,Mandalay,Normal,Female,Home and lifestyle,97.38,10,48.6900,1022.4900,5:16:00 PM,Ewallet,973.80,4.761905,48.6900,4.4,2,3,2019
997,Alex,Yangon,Member,Male,Food and beverages,31.84,1,1.5920,33.4320,1:22:00 PM,Cash,31.84,4.761905,1.5920,7.7,9,2,2019
998,Alex,Yangon,Normal,Male,Home and lifestyle,65.82,1,3.2910,69.1110,3:33:00 PM,Cash,65.82,4.761905,3.2910,4.1,22,2,2019
999,Alex,Yangon,Member,Female,Fashion accessories,88.34,7,30.9190,649.2990,1:28:00 PM,Cash,618.38,4.761905,30.9190,6.6,18,2,2019

In [135]:
df['Time'] = pd.to_datetime(df['Time'])

/tmp/ipykernel_5869/2145562215.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Time'] = pd.to_datetime(df['Time'])

In [136]:
df.dtypes

Branch                             object
City                               object
Customer type                      object
Gender                             object
Product line                       object
Unit price                        float64
Quantity                            int64
Tax 5%                            float64
Sales                             float64
Time                       datetime64[ns]
Payment                            object
cogs                              float64
gross margin percentage           float64
gross income                      float64
Rating                            float64
Day                                 int32
Month                               int32
Year                                int32
dtype: object

In [137]:
df

,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Sales,Time,Payment,cogs,gross margin percentage,gross income,Rating,Day,Month,Year
0,Alex,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,2025-12-04 13:08:00,Ewallet,522.83,4.761905,26.1415,9.1,5,1,2019
1,Giza,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,2025-12-04 10:29:00,Cash,76.40,4.761905,3.8200,9.6,8,3,2019
2,Alex,Yangon,Normal,Female,Home and lifestyle,46.33,7,16.2155,340.5255,2025-12-04 13:23:00,Credit card,324.31,4.761905,16.2155,7.4,3,3,2019
3,Alex,Yangon,Member,Female,Health and beauty,58.22,8,23.2880,489.0480,2025-12-04 20:33:00,Ewallet,465.76,4.761905,23.2880,8.4,27,1,2019
4,Alex,Yangon,Member,Female,Sports and travel,86.31,7,30.2085,634.3785,2025-12-04 10:37:00,Ewallet,604.17,4.761905,30.2085,5.3,8,2,2019
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,Giza,Naypyitaw,Normal,Male,Health and beauty,40.35,1,2.0175,42.3675,2025-12-04 13:46:00,Ewallet,40.35,4.761905,2.0175,6.2,29,1,2019
996,Cairo,Mandalay,Normal,Female,Home and lifestyle,97.38,10,48.6900,1022.4900,2025-12-04 17:16:00,Ewallet,973.80,4.761905,48.6900,4.4,2,3,2019
997,Alex,Yangon,Member,Male,Food and beverages,31.84,1,1.5920,33.4320,2025-12-04 13:22:00,Cash,31.84,4.761905,1.5920,7.7,9,2,2019
998,Alex,Yangon,Normal,Male,Home and lifestyle,65.82,1,3.2910,69.1110,2025-12-04 15:33:00,Cash,65.82,4.761905,3.2910,4.1,22,2,2019
999,Alex,Yangon,Member,Female,Fashion accessories,88.34,7,30.9190,649.2990,2025-12-04 13:28:00,Cash,618.38,4.761905,30.9190,6.6,18,2,2019

In [138]:
def time_of_day(hour):
    if 6 <= hour <12:
        return "Morning"
    elif 12<= hour < 17:
        return "Afternoon"
    elif 17 <= hour < 21:
        return "Evening"
    else:
        return "Night"

In [139]:
df['Hour'] = df['Time'].dt.hour

In [140]:
df['Time_of_Day'] = df['Hour'].apply(time_of_day)

In [141]:
df

,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Sales,Time,Payment,cogs,gross margin percentage,gross income,Rating,Day,Month,Year,Hour,Time_of_Day
0,Alex,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,2025-12-04 13:08:00,Ewallet,522.83,4.761905,26.1415,9.1,5,1,2019,13,Afternoon
1,Giza,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,2025-12-04 10:29:00,Cash,76.40,4.761905,3.8200,9.6,8,3,2019,10,Morning
2,Alex,Yangon,Normal,Female,Home and lifestyle,46.33,7,16.2155,340.5255,2025-12-04 13:23:00,Credit card,324.31,4.761905,16.2155,7.4,3,3,2019,13,Afternoon
3,Alex,Yangon,Member,Female,Health and beauty,58.22,8,23.2880,489.0480,2025-12-04 20:33:00,Ewallet,465.76,4.761905,23.2880,8.4,27,1,2019,20,Evening
4,Alex,Yangon,Member,Female,Sports and travel,86.31,7,30.2085,634.3785,2025-12-04 10:37:00,Ewallet,604.17,4.761905,30.2085,5.3,8,2,2019,10,Morning
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,Giza,Naypyitaw,Normal,Male,Health and beauty,40.35,1,2.0175,42.3675,2025-12-04 13:46:00,Ewallet,40.35,4.761905,2.0175,6.2,29,1,2019,13,Afternoon
996,Cairo,Mandalay,Normal,Female,Home and lifestyle,97.38,10,48.6900,1022.4900,2025-12-04 17:16:00,Ewallet,973.80,4.761905,48.6900,4.4,2,3,2019,17,Evening
997,Alex,Yangon,Member,Male,Food and beverages,31.84,1,1.5920,33.4320,2025-12-04 13:22:00,Cash,31.84,4.761905,1.5920,7.7,9,2,2019,13,Afternoon
998,Alex,Yangon,Normal,Male,Home and lifestyle,65.82,1,3.2910,69.1110,2025-12-04 15:33:00,Cash,65.82,4.761905,3.2910,4.1,22,2,2019,15,Afternoon
999,Alex,Yangon,Member,Female,Fashion accessories,88.34,7,30.9190,649.2990,2025-12-04 13:28:00,Cash,618.38,4.761905,30.9190,6.6,18,2,2019,13,Afternoon

In [ ]:
df = df.drop(columns=['cogs','gross margin percentage','gross income','Time'])

In [143]:
df

,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Sales,Payment,Rating,Day,Month,Year,Hour,Time_of_Day
0,Alex,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,Ewallet,9.1,5,1,2019,13,Afternoon
1,Giza,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,Cash,9.6,8,3,2019,10,Morning
2,Alex,Yangon,Normal,Female,Home and lifestyle,46.33,7,16.2155,340.5255,Credit card,7.4,3,3,2019,13,Afternoon
3,Alex,Yangon,Member,Female,Health and beauty,58.22,8,23.2880,489.0480,Ewallet,8.4,27,1,2019,20,Evening
4,Alex,Yangon,Member,Female,Sports and travel,86.31,7,30.2085,634.3785,Ewallet,5.3,8,2,2019,10,Morning
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,Giza,Naypyitaw,Normal,Male,Health and beauty,40.35,1,2.0175,42.3675,Ewallet,6.2,29,1,2019,13,Afternoon
996,Cairo,Mandalay,Normal,Female,Home and lifestyle,97.38,10,48.6900,1022.4900,Ewallet,4.4,2,3,2019,17,Evening
997,Alex,Yangon,Member,Male,Food and beverages,31.84,1,1.5920,33.4320,Cash,7.7,9,2,2019,13,Afternoon
998,Alex,Yangon,Normal,Male,Home and lifestyle,65.82,1,3.2910,69.1110,Cash,4.1,22,2,2019,15,Afternoon
999,Alex,Yangon,Member,Female,Fashion accessories,88.34,7,30.9190,649.2990,Cash,6.6,18,2,2019,13,Afternoon

In [144]:
df_enc = pd.get_dummies(df[['Branch','City','Customer type','Gender','Product line','Payment','Time_of_Day']],drop_first=True,dtype=int)

In [146]:
df = pd.concat([df,df_enc],axis=1)

In [147]:
df = df.drop(columns=['Branch','City','Customer type','Gender','Product line','Payment','Time_of_Day'])

In [148]:
df

,Unit price,Quantity,Tax 5%,Sales,Rating,Day,Month,Year,Hour,Branch_Cairo,...,Gender_Male,Product line_Fashion accessories,Product line_Food and beverages,Product line_Health and beauty,Product line_Home and lifestyle,Product line_Sports and travel,Payment_Credit card,Payment_Ewallet,Time_of_Day_Evening,Time_of_Day_Morning
0,74.69,7,26.1415,548.9715,9.1,5,1,2019,13,0,...,0,0,0,1,0,0,0,1,0,0
1,15.28,5,3.8200,80.2200,9.6,8,3,2019,10,0,...,0,0,0,0,0,0,0,0,0,1
2,46.33,7,16.2155,340.5255,7.4,3,3,2019,13,0,...,0,0,0,0,1,0,1,0,0,0
3,58.22,8,23.2880,489.0480,8.4,27,1,2019,20,0,...,0,0,0,1,0,0,0,1,1,0
4,86.31,7,30.2085,634.3785,5.3,8,2,2019,10,0,...,0,0,0,0,0,1,0,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,40.35,1,2.0175,42.3675,6.2,29,1,2019,13,0,...,1,0,0,1,0,0,0,1,0,0
996,97.38,10,48.6900,1022.4900,4.4,2,3,2019,17,1,...,0,0,0,0,1,0,0,1,1,0
997,31.84,1,1.5920,33.4320,7.7,9,2,2019,13,0,...,1,0,1,0,0,0,0,0,0,0
998,65.82,1,3.2910,69.1110,4.1,22,2,2019,15,0,...,1,0,0,0,1,0,0,0,0,0
999,88.34,7,30.9190,649.2990,6.6,18,2,2019,13,0,...,0,1,0,0,0,0,0,0,0,0

In [149]:
df.columns

Index(['Unit price', 'Quantity', 'Tax 5%', 'Sales', 'Rating', 'Day', 'Month',
       'Year', 'Hour', 'Branch_Cairo', 'Branch_Giza', 'City_Naypyitaw',
       'City_Yangon', 'Customer type_Normal', 'Gender_Male',
       'Product line_Fashion accessories', 'Product line_Food and beverages',
       'Product line_Health and beauty', 'Product line_Home and lifestyle',
       'Product line_Sports and travel', 'Payment_Credit card',
       'Payment_Ewallet', 'Time_of_Day_Evening', 'Time_of_Day_Morning'],
      dtype='object')

In [150]:
x = df.drop(columns='Rating')

In [152]:
y = df['Rating']

In [153]:
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=42)

In [154]:
from sklearn.ensemble import RandomForestRegressor
model = RandomForestRegressor(n_estimators=150,n_jobs=-1)

model.fit(x_train,y_train)

RandomForestRegressor(n_estimators=150, n_jobs=-1)

In [155]:
y_pred  = model.predict(x_test)

In [156]:
from sklearn.metrics import mean_absolute_percentage_error,r2_score

mean_absolute_percentage_error(y_test,y_pred)

0.2495702202590611

In [157]:
r2_score(y_test,y_pred)

-0.11089078181595857